"""add_preview_image_to_camera

Revision ID: e7532876441e
Revises: 1321fd4c1406
Create Date: 2025-12-16 20:39:04.312244

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e7532876441e"
down_revision: Union[str, None] = "1321fd4c1406"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cameras", sa.Column("preview_image", sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cameras", "preview_image")
    # ### end Alembic commands ###
